INCLUDEPATH += "C:/Program Files/GnuWin32/include"

HEADERS += main.h \
           gsl/include/gsl/config.h \
           gsl/include/gsl/gsl_blas.h \
           gsl/include/gsl/gsl_blas_types.h \
           gsl/include/gsl/gsl_block.h \
           gsl/include/gsl/gsl_block_char.h \
           gsl/include/gsl/gsl_block_complex_double.h \
           gsl/include/gsl/gsl_block_complex_float.h \
           gsl/include/gsl/gsl_block_complex_long_double.h \
           gsl/include/gsl/gsl_block_double.h \
           gsl/include/gsl/gsl_block_float.h \
           gsl/include/gsl/gsl_block_int.h \
           gsl/include/gsl/gsl_block_long.h \
           gsl/include/gsl/gsl_block_long_double.h \
           gsl/include/gsl/gsl_block_short.h \
           gsl/include/gsl/gsl_block_uchar.h \
           gsl/include/gsl/gsl_block_uint.h \
           gsl/include/gsl/gsl_block_ulong.h \
           gsl/include/gsl/gsl_block_ushort.h \
           gsl/include/gsl/gsl_cblas.h \
           gsl/include/gsl/gsl_cdf.h \
           gsl/include/gsl/gsl_chebyshev.h \
           gsl/include/gsl/gsl_check_range.h \
           gsl/include/gsl/gsl_combination.h \
           gsl/include/gsl/gsl_complex.h \
           gsl/include/gsl/gsl_complex_math.h \
           gsl/include/gsl/gsl_const.h \
           gsl/include/gsl/gsl_const_cgs.h \
           gsl/include/gsl/gsl_const_cgsm.h \
           gsl/include/gsl/gsl_const_mks.h \
           gsl/include/gsl/gsl_const_mksa.h \
           gsl/include/gsl/gsl_const_num.h \
           gsl/include/gsl/gsl_deriv.h \
           gsl/include/gsl/gsl_dft_complex.h \
           gsl/include/gsl/gsl_dft_complex_float.h \
           gsl/include/gsl/gsl_dht.h \
           gsl/include/gsl/gsl_diff.h \
           gsl/include/gsl/gsl_eigen.h \
           gsl/include/gsl/gsl_errno.h \
           gsl/include/gsl/gsl_fft.h \
           gsl/include/gsl/gsl_fft_complex.h \
           gsl/include/gsl/gsl_fft_complex_float.h \
           gsl/include/gsl/gsl_fft_halfcomplex.h \
           gsl/include/gsl/gsl_fft_halfcomplex_float.h \
           gsl/include/gsl/gsl_fft_real.h \
           gsl/include/gsl/gsl_fft_real_float.h \
           gsl/include/gsl/gsl_fit.h \
           gsl/include/gsl/gsl_heapsort.h \
           gsl/include/gsl/gsl_histogram.h \
           gsl/include/gsl/gsl_histogram2d.h \
           gsl/include/gsl/gsl_ieee_utils.h \
           gsl/include/gsl/gsl_integration.h \
           gsl/include/gsl/gsl_interp.h \
           gsl/include/gsl/gsl_linalg.h \
           gsl/include/gsl/gsl_machine.h \
           gsl/include/gsl/gsl_math.h \
           gsl/include/gsl/gsl_matrix.h \
           gsl/include/gsl/gsl_matrix_char.h \
           gsl/include/gsl/gsl_matrix_complex_double.h \
           gsl/include/gsl/gsl_matrix_complex_float.h \
           gsl/include/gsl/gsl_matrix_complex_long_double.h \
           gsl/include/gsl/gsl_matrix_double.h \
           gsl/include/gsl/gsl_matrix_float.h \
           gsl/include/gsl/gsl_matrix_int.h \
           gsl/include/gsl/gsl_matrix_long.h \
           gsl/include/gsl/gsl_matrix_long_double.h \
           gsl/include/gsl/gsl_matrix_short.h \
           gsl/include/gsl/gsl_matrix_uchar.h \
           gsl/include/gsl/gsl_matrix_uint.h \
           gsl/include/gsl/gsl_matrix_ulong.h \
           gsl/include/gsl/gsl_matrix_ushort.h \
           gsl/include/gsl/gsl_message.h \
           gsl/include/gsl/gsl_min.h \
           gsl/include/gsl/gsl_mode.h \
           gsl/include/gsl/gsl_monte.h \
           gsl/include/gsl/gsl_monte_miser.h \
           gsl/include/gsl/gsl_monte_plain.h \
           gsl/include/gsl/gsl_monte_vegas.h \
           gsl/include/gsl/gsl_multifit.h \
           gsl/include/gsl/gsl_multifit_nlin.h \
           gsl/include/gsl/gsl_multimin.h \
           gsl/include/gsl/gsl_multiroots.h \
           gsl/include/gsl/gsl_nan.h \
           gsl/include/gsl/gsl_ntuple.h \
           gsl/include/gsl/gsl_odeiv.h \
           gsl/include/gsl/gsl_permutation.h \
           gsl/include/gsl/gsl_permute.h \
           gsl/include/gsl/gsl_permute_char.h \
           gsl/include/gsl/gsl_permute_complex_double.h \
           gsl/include/gsl/gsl_permute_complex_float.h \
           gsl/include/gsl/gsl_permute_complex_long_double.h \
           gsl/include/gsl/gsl_permute_double.h \
           gsl/include/gsl/gsl_permute_float.h \
           gsl/include/gsl/gsl_permute_int.h \
           gsl/include/gsl/gsl_permute_long.h \
           gsl/include/gsl/gsl_permute_long_double.h \
           gsl/include/gsl/gsl_permute_short.h \
           gsl/include/gsl/gsl_permute_uchar.h \
           gsl/include/gsl/gsl_permute_uint.h \
           gsl/include/gsl/gsl_permute_ulong.h \
           gsl/include/gsl/gsl_permute_ushort.h \
           gsl/include/gsl/gsl_permute_vector.h \
           gsl/include/gsl/gsl_permute_vector_char.h \
           gsl/include/gsl/gsl_permute_vector_complex_double.h \
           gsl/include/gsl/gsl_permute_vector_complex_float.h \
           gsl/include/gsl/gsl_permute_vector_complex_long_double.h \
           gsl/include/gsl/gsl_permute_vector_double.h \
           gsl/include/gsl/gsl_permute_vector_float.h \
           gsl/include/gsl/gsl_permute_vector_int.h \
           gsl/include/gsl/gsl_permute_vector_long.h \
           gsl/include/gsl/gsl_permute_vector_long_double.h \
           gsl/include/gsl/gsl_permute_vector_short.h \
           gsl/include/gsl/gsl_permute_vector_uchar.h \
           gsl/include/gsl/gsl_permute_vector_uint.h \
           gsl/include/gsl/gsl_permute_vector_ulong.h \
           gsl/include/gsl/gsl_permute_vector_ushort.h \
           gsl/include/gsl/gsl_poly.h \
           gsl/include/gsl/gsl_pow_int.h \
           gsl/include/gsl/gsl_precision.h \
           gsl/include/gsl/gsl_qrng.h \
           gsl/include/gsl/gsl_randist.h \
           gsl/include/gsl/gsl_rng.h \
           gsl/include/gsl/gsl_roots.h \
           gsl/include/gsl/gsl_sf.h \
           gsl/include/gsl/gsl_sf_airy.h \
           gsl/include/gsl/gsl_sf_bessel.h \
           gsl/include/gsl/gsl_sf_clausen.h \
           gsl/include/gsl/gsl_sf_coulomb.h \
           gsl/include/gsl/gsl_sf_coupling.h \
           gsl/include/gsl/gsl_sf_dawson.h \
           gsl/include/gsl/gsl_sf_debye.h \
           gsl/include/gsl/gsl_sf_dilog.h \
           gsl/include/gsl/gsl_sf_elementary.h \
           gsl/include/gsl/gsl_sf_ellint.h \
           gsl/include/gsl/gsl_sf_elljac.h \
           gsl/include/gsl/gsl_sf_erf.h \
           gsl/include/gsl/gsl_sf_exp.h \
           gsl/include/gsl/gsl_sf_expint.h \
           gsl/include/gsl/gsl_sf_fermi_dirac.h \
           gsl/include/gsl/gsl_sf_gamma.h \
           gsl/include/gsl/gsl_sf_gegenbauer.h \
           gsl/include/gsl/gsl_sf_hyperg.h \
           gsl/include/gsl/gsl_sf_laguerre.h \
           gsl/include/gsl/gsl_sf_lambert.h \
           gsl/include/gsl/gsl_sf_legendre.h \
           gsl/include/gsl/gsl_sf_log.h \
           gsl/include/gsl/gsl_sf_pow_int.h \
           gsl/include/gsl/gsl_sf_psi.h \
           gsl/include/gsl/gsl_sf_result.h \
           gsl/include/gsl/gsl_sf_synchrotron.h \
           gsl/include/gsl/gsl_sf_transport.h \
           gsl/include/gsl/gsl_sf_trig.h \
           gsl/include/gsl/gsl_sf_zeta.h \
           gsl/include/gsl/gsl_siman.h \
           gsl/include/gsl/gsl_sort.h \
           gsl/include/gsl/gsl_sort_char.h \
           gsl/include/gsl/gsl_sort_double.h \
           gsl/include/gsl/gsl_sort_float.h \
           gsl/include/gsl/gsl_sort_int.h \
           gsl/include/gsl/gsl_sort_long.h \
           gsl/include/gsl/gsl_sort_long_double.h \
           gsl/include/gsl/gsl_sort_short.h \
           gsl/include/gsl/gsl_sort_uchar.h \
           gsl/include/gsl/gsl_sort_uint.h \
           gsl/include/gsl/gsl_sort_ulong.h \
           gsl/include/gsl/gsl_sort_ushort.h \
           gsl/include/gsl/gsl_sort_vector.h \
           gsl/include/gsl/gsl_sort_vector_char.h \
           gsl/include/gsl/gsl_sort_vector_double.h \
           gsl/include/gsl/gsl_sort_vector_float.h \
           gsl/include/gsl/gsl_sort_vector_int.h \
           gsl/include/gsl/gsl_sort_vector_long.h \
           gsl/include/gsl/gsl_sort_vector_long_double.h \
           gsl/include/gsl/gsl_sort_vector_short.h \
           gsl/include/gsl/gsl_sort_vector_uchar.h \
           gsl/include/gsl/gsl_sort_vector_uint.h \
           gsl/include/gsl/gsl_sort_vector_ulong.h \
           gsl/include/gsl/gsl_sort_vector_ushort.h \
           gsl/include/gsl/gsl_specfunc.h \
           gsl/include/gsl/gsl_spline.h \
           gsl/include/gsl/gsl_statistics.h \
           gsl/include/gsl/gsl_statistics_char.h \
           gsl/include/gsl/gsl_statistics_double.h \
           gsl/include/gsl/gsl_statistics_float.h \
           gsl/include/gsl/gsl_statistics_int.h \
           gsl/include/gsl/gsl_statistics_long.h \
           gsl/include/gsl/gsl_statistics_long_double.h \
           gsl/include/gsl/gsl_statistics_short.h \
           gsl/include/gsl/gsl_statistics_uchar.h \
           gsl/include/gsl/gsl_statistics_uint.h \
           gsl/include/gsl/gsl_statistics_ulong.h \
           gsl/include/gsl/gsl_statistics_ushort.h \
           gsl/include/gsl/gsl_sum.h \
           gsl/include/gsl/gsl_sys.h \
           gsl/include/gsl/gsl_test.h \
           gsl/include/gsl/gsl_types.h \
           gsl/include/gsl/gsl_vector.h \
           gsl/include/gsl/gsl_vector_char.h \
           gsl/include/gsl/gsl_vector_complex.h \
           gsl/include/gsl/gsl_vector_complex_double.h \
           gsl/include/gsl/gsl_vector_complex_float.h \
           gsl/include/gsl/gsl_vector_complex_long_double.h \
           gsl/include/gsl/gsl_vector_double.h \
           gsl/include/gsl/gsl_vector_float.h \
           gsl/include/gsl/gsl_vector_int.h \
           gsl/include/gsl/gsl_vector_long.h \
           gsl/include/gsl/gsl_vector_long_double.h \
           gsl/include/gsl/gsl_vector_short.h \
           gsl/include/gsl/gsl_vector_uchar.h \
           gsl/include/gsl/gsl_vector_uint.h \
           gsl/include/gsl/gsl_vector_ulong.h \
           gsl/include/gsl/gsl_vector_ushort.h \
           gsl/include/gsl/gsl_version.h \
           gsl/include/gsl/gsl_wavelet.h \
           gsl/include/gsl/gsl_wavelet2d.h
SOURCES += dip.cpp \
    erroy.cpp

LIBS += "C:/Program Files/GnuWin32/lib/libgsl.a"
LIBS += "C:/Program Files/GnuWin32/lib/libgslcblas.a"

